# Generated by Django 4.2.2 on 2023-06-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='app.mark', verbose_name='Номер Марки'),
        ),
        migrations.AlterField(
            model_name='code',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='app.mark', verbose_name='Номер Марки'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent', to='app.mark', verbose_name='Номер Марки'),
        ),
    ]
