# Generated by Django 4.2.2 on 2023-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_applicant_mark_alter_code_mark_alter_mark_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='img',
            field=models.CharField(max_length=255, verbose_name='Замещающий текст'),
        ),
    ]
